_root.id = _root.id + 1;
io = new Object();
io._x = 150;
grn.attachMovie("tractor2","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 110;
grn.attachMovie("tank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 190;
grn.attachMovie("tank","en" + _root.id,_root.id,io);
