_root.id = _root.id + 1;
sky.attachMovie("fly5","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 60;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 241;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
