_root.id = _root.id + 1;
io = new Object();
io._y = 240;
grn.attachMovie("wtank2","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 280;
grn.attachMovie("wtank5","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 80;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 180;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
