_root.id = _root.id + 1;
sky.attachMovie("glider","en" + _root.id,_root.id);
_root.id = _root.id + 1;
sky.attachMovie("glider","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 80;
grn.attachMovie("utank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 220;
grn.attachMovie("utank","en" + _root.id,_root.id,io);
