_root.id = _root.id + 1;
io = new Object();
io._x = 64;
grn.attachMovie("magicbush","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 16;
grn.attachMovie("stump","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 112;
grn.attachMovie("stump","en" + _root.id,_root.id,io);
