_root.id = _root.id + 1;
io = new Object();
io._x = 80;
io._y = 192;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 257;
grn.attachMovie("lift","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 150;
grn.attachMovie("box","en" + _root.id,_root.id,io);
