_root.id = _root.id + 1;
sky.attachMovie("fly5","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 20;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 50;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
