_root.id = _root.id + 1;
io = new Object();
io._x = 24;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 56;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 88;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 120;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
