_root.id = _root.id + 1;
io = new Object();
io._x = 24;
io._y = 144;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 270;
io._y = 144;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
