_root.id = _root.id + 1;
sky.attachMovie("kami","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 180;
io._y = 248;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 256;
io._y = 248;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
