_root.id = _root.id + 1;
sky.attachMovie("fly5","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 16;
io._y = 100;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 284;
io._y = 100;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
