rt -= rate;
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = xp - 25;
initObject._y = yp + 42;
initObject._rotation = 180 - rt;
_root.itemc.attachMovie("shot","shot" + _root.id,_root.id,initObject);
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = xp - 25;
initObject._y = yp + 42;
initObject._rotation = 180 + rt;
_root.itemc.attachMovie("shot","shot" + _root.id,_root.id,initObject);
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = xp + 25;
initObject._y = yp + 42;
initObject._rotation = 180 - rt;
_root.itemc.attachMovie("shot","shot" + _root.id,_root.id,initObject);
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = xp + 25;
initObject._y = yp + 42;
initObject._rotation = 180 + rt;
_root.itemc.attachMovie("shot","shot" + _root.id,_root.id,initObject);
