_root.id = _root.id + 1;
sky.attachMovie("glider","en" + _root.id,_root.id);
_root.id = _root.id + 1;
sky.attachMovie("glider","en" + _root.id,_root.id);
_root.id = _root.id + 1;
air.attachMovie("bomber2","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 240;
grn.attachMovie("utank","en" + _root.id,_root.id,io);
