_root.id = _root.id + 1;
io = new Object();
io._x = 80;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 120;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 160;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 200;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
