_root.id = _root.id + 1;
io = new Object();
io._x = 20;
io._y = 80;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 280;
io._y = 80;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
