_root.id = _root.id + 1;
io = new Object();
io._x = 68;
grn.attachMovie("gtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 192;
grn.attachMovie("box","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 240;
grn.attachMovie("container","en" + _root.id,_root.id,io);
