_root.id = _root.id + 1;
io = new Object();
io._x = 136;
grn.attachMovie("container","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 60;
grn.attachMovie("tank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 100;
grn.attachMovie("tank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 220;
grn.attachMovie("gtank","en" + _root.id,_root.id,io);
