_root.id = _root.id + 1;
sky.attachMovie("fly3","en" + _root.id,_root.id);
_root.id = _root.id + 1;
sky.attachMovie("fly3","en" + _root.id,_root.id);
_root.id = _root.id + 1;
sky.attachMovie("fly3","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._y = 32;
grn.attachMovie("wtank2z","en" + _root.id,_root.id,io);
