_root.id = _root.id + 1;
io = new Object();
io._x = 270;
io._y = 112;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 130;
io._y = 260;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
