_root.id = _root.id + 1;
io = new Object();
io._x = 24;
grn.attachMovie("wtank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 72;
grn.attachMovie("wtank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 270;
io._rotation = 90;
grn.attachMovie("struc","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 180;
grn.attachMovie("struc","en" + _root.id,_root.id,io);
