_root.id = _root.id + 1;
sky.attachMovie("glider","en" + _root.id,_root.id);
_root.id = _root.id + 1;
sky.attachMovie("glider","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 20;
grn.attachMovie("box","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
air.attachMovie("copter","en" + _root.id,_root.id);
