_root.id = _root.id + 1;
sky.attachMovie("fly4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 80;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 218;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
