_root.id = _root.id + 1;
sky.attachMovie("fly3","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 150;
grn.attachMovie("wtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 37;
grn.attachMovie("box","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 259;
grn.attachMovie("box","en" + _root.id,_root.id,io);
