_root.id = _root.id + 1;
io = new Object();
io._x = 112;
io._y = 96;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 64;
io._y = 200;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
