_root.id = _root.id + 1;
air.attachMovie("satellite","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 50;
grn.attachMovie("ttank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 250;
grn.attachMovie("ttank","en" + _root.id,_root.id,io);
