_root.id = _root.id + 1;
sky.attachMovie("fly5","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 110;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 190;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 70;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 230;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
