_root.id = _root.id + 1;
sky.attachMovie("fly4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
sky.attachMovie("fly4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._y = 214;
grn.attachMovie("tank2z","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._y = 246;
grn.attachMovie("tank2z","en" + _root.id,_root.id,io);
