_root.id = _root.id + 1;
sky.attachMovie("fly3","en" + _root.id,_root.id);
_root.id = _root.id + 1;
sky.attachMovie("fly3","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 216;
grn.attachMovie("submarine","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 150;
grn.attachMovie("wtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 275;
grn.attachMovie("wtank","en" + _root.id,_root.id,io);
