_root.id = _root.id + 1;
io = new Object();
io._x = 30;
grn.attachMovie("pillar","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 110;
grn.attachMovie("pillar","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 190;
grn.attachMovie("pillar","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 270;
grn.attachMovie("pillar","en" + _root.id,_root.id,io);
