generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
generate();
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = _parent.xp;
initObject._y = _parent.yp;
_root.itemc.attachMovie("1up","item" + _root.id,_root.id,initObject);
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = _parent.xp;
initObject._y = _parent.yp;
_root.itemc.attachMovie("ruby","ruby" + _root.id,_root.id,initObject);
_root.score += Math.round(_root.dif * 5000 / 10) * 10;
_parent.gone = 1;
_parent.gotoAndStop(2);
