_parent.gone = 1;
_root.lv1.planeArray[_parent.adt] = null;
_root.lv1.upd();
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = _parent.xp;
initObject._y = _parent.yp;
_root.lv1.rtanks.attachMovie("diamond2","diamond" + _root.id,_root.id,initObject);
fly.gotoAndStop(1);
_root.score += Math.round(_root.dif * 6400 / 10) * 10;
