_root.id = _root.id + 1;
sky.attachMovie("kami","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 34;
grn.attachMovie("stump","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 94;
grn.attachMovie("stump","en" + _root.id,_root.id,io);
