_root.id = _root.id + 1;
sky.attachMovie("vulturer","en" + _root.id,_root.id);
_root.id = _root.id + 1;
sky.attachMovie("vulturel","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 56;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 96;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 136;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 176;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 24;
io._y = 96;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 276;
io._y = 96;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
