_root.id = _root.id + 1;
initObject = new Object();
initObject._x = _parent._x + _X - 6;
initObject._y = _parent._y + _Y - 24;
_root.cont.attachMovie("preblast","hit" + _root.id,_root.id,initObject);
_root.id = _root.id + 1;
initObject = new Object();
initObject._x = _parent._x + _X + 6;
initObject._y = _parent._y + _Y - 24;
_root.cont.attachMovie("preblast","hit" + _root.id,_root.id,initObject);
_parent.gotoAndStop(1);
stop();
