_root.id = _root.id + 1;
io = new Object();
io._x = 243;
grn.attachMovie("tank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
air.attachMovie("satellite","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 160;
io._y = 256;
grn.attachMovie("rtank","en" + _root.id,_root.id,io);
