_root.id = _root.id + 1;
io = new Object();
io._x = 140;
grn.attachMovie("stump","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 211;
grn.attachMovie("container","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 280;
grn.attachMovie("stump","en" + _root.id,_root.id,io);
