function swarm()
{
   var _loc1_ = _root;
   _loc1_.id = _loc1_.id + 1;
   initObject = new Object();
   initObject._x = xp;
   initObject._y = yp;
   initObject.rota = 15;
   _loc1_.itemc.attachMovie("pappear","itm" + _loc1_.id,_loc1_.id,initObject);
   _loc1_.id = _loc1_.id + 1;
   initObject = new Object();
   initObject._x = xp;
   initObject._y = yp;
   initObject.rota = 345;
   _loc1_.itemc.attachMovie("pappear","itm" + _loc1_.id,_loc1_.id,initObject);
   _loc1_.id = _loc1_.id + 1;
   initObject = new Object();
   initObject._x = xp;
   initObject._y = yp;
   initObject.rota = 35;
   _loc1_.itemc.attachMovie("pappear","itm" + _loc1_.id,_loc1_.id,initObject);
   _loc1_.id = _loc1_.id + 1;
   initObject = new Object();
   initObject._x = xp;
   initObject._y = yp;
   initObject.rota = 325;
   _loc1_.itemc.attachMovie("pappear","itm" + _loc1_.id,_loc1_.id,initObject);
   _loc1_.id = _loc1_.id + 1;
   initObject = new Object();
   initObject._x = xp;
   initObject._y = yp;
   initObject.rota = 55;
   _loc1_.itemc.attachMovie("pappear","itm" + _loc1_.id,_loc1_.id,initObject);
   _loc1_.id = _loc1_.id + 1;
   initObject = new Object();
   initObject._x = xp;
   initObject._y = yp;
   initObject.rota = 305;
   _loc1_.itemc.attachMovie("pappear","itm" + _loc1_.id,_loc1_.id,initObject);
}
