_root.id = _root.id + 1;
sky.attachMovie("kami","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 32;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 96;
grn.attachMovie("tank4","en" + _root.id,_root.id,io);
