_root.id = _root.id + 1;
sky.attachMovie("fly4","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 16;
grn.attachMovie("box","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 216;
grn.attachMovie("tank3","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
air.attachMovie("satellite","en" + _root.id,_root.id,io);
