_root.id = _root.id + 1;
sky.attachMovie("fly5","en" + _root.id,_root.id);
_root.id = _root.id + 1;
io = new Object();
io._x = 30;
grn.attachMovie("gtank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 270;
grn.attachMovie("gtank","en" + _root.id,_root.id,io);
