_root.id = _root.id + 1;
io = new Object();
io._x = 175;
grn.attachMovie("tractor2","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 135;
grn.attachMovie("tank","en" + _root.id,_root.id,io);
_root.id = _root.id + 1;
io = new Object();
io._x = 215;
grn.attachMovie("tank","en" + _root.id,_root.id,io);
